import * as React from 'react';

import { Dag } from '../model/dag';
import Slider from './Slider';
import Graph from './Graph';
import ReactModal from 'react-modal';
ReactModal.setAppElement('#root');

type Props = {
  dag: Dag,
  passiveDag: Dag | null,
  nodeSelection: number[],
  changedNodesEvent?: Set<number>,
  historyLength: number,
  currentTime: number,
  onNodeSelectionChange: (selection: number[]) => void,
  onCurrentTimeChange: (newState: number) => void,
  onShowPassiveDag: (selectionId: number, currentTime: number) => void,
  onDismissPassiveDag: (selectedId: number | null) => void,
  onUpdateNodePosition: (nodeId: number, delta: [number, number]) => void
};
export default class Main extends React.Component<Props, {}> {

  render() {
    let modal;
    if (this.props.passiveDag !== null) {
      modal =
      <ReactModal
        isOpen={this.props.passiveDag !== null}
        contentLabel={`Clauses currently in Passive generated by clause with id ${this.props.passiveDag!.activeNodeId!}`}
        onRequestClose={() => {this.props.onDismissPassiveDag(null);}}
      >
        <Graph
          dag={this.props.passiveDag}
          nodeSelection={this.props.nodeSelection}
          changedNodesEvent={this.props.changedNodesEvent}
          currentTime={this.props.currentTime}
          onNodeSelectionChange={this.props.onNodeSelectionChange}
          onShowPassiveDag={this.props.onShowPassiveDag}
          onDismissPassiveDag={this.props.onDismissPassiveDag}
          onUpdateNodePosition={this.props.onUpdateNodePosition}
        />
      </ReactModal>  
    }

    return (
      <main>
        <Graph
          dag={this.props.dag}
          nodeSelection={this.props.nodeSelection}
          changedNodesEvent={this.props.changedNodesEvent}
          currentTime={this.props.currentTime}
          onNodeSelectionChange={this.props.onNodeSelectionChange}
          onShowPassiveDag={this.props.onShowPassiveDag}
          onDismissPassiveDag={this.props.onDismissPassiveDag}
          onUpdateNodePosition={this.props.onUpdateNodePosition}
        />
        {modal}
        <Slider
          historyLength={this.props.historyLength}
          currentTime={this.props.currentTime}
          onCurrentTimeChange={this.props.onCurrentTimeChange}
          enabled={!this.props.dag.isPassiveDag}
        />
      </main>
    );
  }

}
