import * as React from 'react';

import './NodeDetails.css';
import Sortable from 'react-sortablejs';
import { Clause } from '../model/unit';
import { Literal } from '../model/literal';
import SatNode from '../model/sat-node';

type Props = {
    node: any,
};

export default class NodeDetails extends React.Component<Props, {}> {

    keep = false; // hack to skip each second event generated by Sortable

    render() {
        return (
            <section className= { 'component-node-details details'} >
            <article>
            <h2>Node < strong > { this.props.node.nodeId }, </strong></h2 >
                <pre>{this.props.node.expr}</pre>
            </article>
            </section>
    );
    }

}
